name: MyBlockChain CI

on:
  pull_request:
  push:

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run unit tests
        run: npm test

      - name: Run coverage
        run: npm run coverage
  
  eslint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - run: npm ci
      - run: npm run lint